# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-NicoVideo
version:      0.01
version_from: lib/WWW/NicoVideo.pm
installdirs:  site
requires:
    LWP:                           5.8
    Web::Scraper:                  0.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
